# Generated by Django 5.1.6 on 2025-02-24 02:34

import club.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_member_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='member_images/', validators=[club.models.validate_image_file]),
        ),
    ]
